name: Discord Webhook
on: [push]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Run Discord Webhook
      uses: mbouazza-dev/RMI-WebService/.github/workflows@main
      with:
        id: 898549731603648513
        token: ZfYGiBkS14om-ghR0LTzDGq3U653sWjZDRbh_d7ZuOtP40stHO89vKSrhulqiz8hFE2E